# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    fos_user.doctrine_registry:
        alias: doctrine
        
    authentication.handler.login_success_handler:
        class:  AppBundle\Security\Authentication\Handler\LoginSuccessHandler
        arguments:  ['@router', '@security.authorization_checker','@doctrine.orm.entity_manager']
        
    app.form.registration:
        class: AppBundle\Form\RegistrationType
        tags:
            - { name: form.type, alias: app_user_registration }
                        
    app.form.edituser:
        class: AppBundle\Form\ProfileEditType
        tags:
            - { name: form.type, alias: app_user_profile }
    
    app.photo_uploader:
        class: AppBundle\FileUploader
        arguments: ['%photos_directory%']
    
    app.doctrine_photo_listener:
        class: AppBundle\EventListener\PhotoUploadListener
        arguments: ['@app.photo_uploader']
        tags:
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: preUpdate }
            - { name: doctrine.event_listener, event: postLoad }            
   
    app.doctrine_course:
        class: AppBundle\EventListener\CourseListener        
        tags:
            - { name: doctrine.event_listener, event: postLoad }        
    
    app.twig_extension:
        class: AppBundle\Twig\AppExtension
        public: false
        tags:
            - { name: twig.extension }